steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', "gcr.io/$PROJECT_ID/fgf-core:v$BUILD_ID", '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', "gcr.io/$PROJECT_ID/fgf-core:v$BUILD_ID"]
    env:
    - CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}
    - CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}
    - DB_USER=${_DB_USER}
    - DB_PASSWORD=${_DB_PASSWORD}
    - DB_HOST=${_DB_HOST}
    - DB_PORT=${_DB_PORT}
    - DB_NAME=${_DB_NAME}